### PR TITLE
Added symlink functionality

### PR DESCRIPTION
**Pull request by hellisabove**

### CODE REVIEW

**Comment by Hunam6** [comment]
This will not work on Windows, plus on some other linux distros.
See how V did it: https://github.com/vlang/v/blob/master/cmd/tools/vsymlink.v.
I think there should be a quick and easy way to symlink a program, a way similar to how `v symlink` works and similar to `os.symlink`'s usage.

**Comment by hellisabove** [comment]
I have updated the process. It now works on my hackintosh and my windows laptop.

**Comment by Hunam6** [comment]
Nice initiative, here's my reviews:
- You included a binary by mistake in the PR, please remove it until I add a corresponding gitignore entry for this later
- `vsymlink.v` needs to be put in a folder to be imported, see https://github.com/vlang/v/blob/master/doc/docs.md#modules
- Are you sure it really work, for me it links to V binary, see

Screenshot 2022-02-04 at 22 37 43

- It also reproduces the same behaviour on my Windows machine.

- I agree with you and I think that's a good idea to have a `version` command, but IMHO this should go in a separate PR, and you should also create that PR with a working implementation, see https://github.com/vlang/v/blob/master/cmd/tools/vdoctor.v

**Comment by hellisabove** [comment]
I don't know why id won't work for you. For me it works on both machines.
Screenshot 2022-02-05 at 00 16 14
I don't have access to my windows laptop right now but it show the same thing.

**Comment by Hunam6** [comment]
I re-git-pulled your PR, deleted the alias, tested it it was really removed, re-launched the `symlink` command and:
Screenshot 2022-02-04 at 23 32 56
 
Maybe during your testing you did something that worked and the file was kept. Try removing the file maybe?

Anyway that'll be the last comment from me today, it's getting late 👋

**Comment by hellisabove** [comment]
I removed it, removed the repo, re-cloned the repo, compile and symlink and it work for me. I got the screenshot from my windows machine now.
Screenshot (1)
Did the same thing on both machines and everything and it links correctly. Good night man

**Comment by Hunam6** [comment]
Screenshot 2022-02-05 at 18 35 15
This line refers to the V exe, the issue may come from this

**Comment by Hunam6** [comment]
Still
Screenshot 2022-02-05 at 18 36 48

**Comment by JalonSolov** [comment]
Question:  Have you tried using the `mklink` command on Windows, instead of this whole .bat file idea?  `mklink` has supposedly been included with Windows since Windows 7.  If it isn't available, could always fall back to the .bat file as the alternative.

**Comment by hellisabove** [comment]
Btw, what version of v are you using? Cause I put both 'os.executable()' and 'os.real_path(pref.vexe_path())' into an example program and when printing the variable they give the path of the executable. I'm using the latest version on the git page

**Comment by hellisabove** [comment]
> Question: Have you tried using the `mklink` command on Windows, instead of this whole .bat file idea? `mklink` has supposedly been included with Windows since Windows 7. If it isn't available, could always fall back to the .bat file as the alternative.

I actually haven't tried this as I work on macos or linux most of the time.Thanks for suggesting this, I'll try and see if it works

**Comment by JalonSolov** [comment]
Please merge the latest changes from master, or at least remove your .gitignore change from this PR - that's been added already.

**Comment by hellisabove** [comment]
So do I remove the .gitignore from my repo or just delete the entries?

**Comment by JalonSolov** [comment]
If you delete the entry you added, then push that change to the PR, it will remove the .gitignore change from the PR... I think.  Git is picky, sometimes, but that's what should happen.

**Comment by JalonSolov** [comment]
Looks like it worked - thanks!  :-)

**Comment by Hunam6** [comment]
Those commits when merged will have to be merged together in one commit (I think it's called rebased), otherwise the commit history will get really dirty

**Comment by JalonSolov** [comment]
That's the way it is set up.  The button I see says "Squash and merge", meaning all the commits are "squashed" into one, then that one commit is merged.

**Pull request closed without merging**
