### PR TITLE
fix: better output path handling

### LINKED ISSUE #23: cannot overwrite a file with `-o` set
Same as #18 but only when `-o` is specified.
Steps to reproduce:
```
touch file.go // file.go gets created
v run . file.go -o out.v // out.v gets created
v run . file.go -o out.v //error
```
I get `cli execution error: failed to open file "out.v/out.v"`

### PR DESCRIPTION
**Pull request by JalonSolov**
Fixes #23

### CODE REVIEW

**Review by Hunam6 — CHANGES_REQUESTED** [review]
Running this
```
touch file.go // file.go gets created
v run . file.go -o out.v // error
```
creates a folder named `out.v`, inside this folder it creates a file named `file.v` (with the translated go file `file.go`)

**Comment by JalonSolov** [comment]
Fixed that issue, as well as allowing you to do something like `go2v file.go -o out/` to explicitly create `out/file.v` instead of a file named `out`.  In other words, trailing slash means output directory when the input is a file.

Could be useful for all_test.v - send the output to `/tmp/` so it has the same name as the go file, diff it with the .vv file, then delete it.  That way there are no extra files left lying around in the go2v tests/* dirs, and no need to the .gitignore to keep them from getting pushed.

**Review by Hunam6 — CHANGES_REQUESTED** [review]
Looking almost perfect, one last bug I found
```
hunam@Hunam-Mac go2v_check % touch file.go
hunam@Hunam-Mac go2v_check % v run . file.go -o out
hunam@Hunam-Mac go2v_check % v run . file.go -o out/
cli execution error: failed to open file "out/file.v"
```

**Comment by Hunam6** [comment]
I'm confused, you said

> allowing you to do something like go2v file.go -o out/ to explicitly create out/file.v instead of a file named out. In other words, trailing slash means output directory when the input is a file.

I may be wrong but according to what you said this should result in the file `out` created, the dir `out` created and the file `file.v` created inside of the dir `out`, right?
```
hunam@Hunam-Mac go2v_check % touch file.go
hunam@Hunam-Mac go2v_check % v run . file.go -o out
hunam@Hunam-Mac go2v_check % v run . file.go -o out/
cli execution error: 'out' is a file, not a directory
```

**Comment by JalonSolov** [comment]
You are correct.  But in this case, you already created `out` as a file, and you can't mkdir a directory with the same name as an existing file, hence the error message.

It would be a bad idea to have go2v delete the file first, then make a directory with the same name.

**Comment by Hunam6** [comment]
Oh you're right, I wasn't aware of this "limitation"
Screenshot 2022-02-09 at 16 23 29

> It would be a bad idea to have go2v delete the file first, then make a directory with the same name.

Yes it would be

Is a custom error message to explain that
```
cannot create the file 'out' as the directory 'out' exists
```
is applicable?

**Comment by Hunam6** [comment]
Also, a **tiny** issue, when the program throws an error it uses double quotes (`cli execution error: failed to open file "out/file.v"`) but in every of our custom error but one we used single quotes, as I don't think we can change default ones, we should probably also adopt this format

**Comment by JalonSolov** [comment]
I mean, a custom error message especially for this error of mkdir not possible when a file with the same name already exists

**Comment by Hunam6** [comment]
Sorry I edited your message by mistake, I just wanted to add a new message, I can't undo it :/

**Comment by JalonSolov** [comment]
The error `'"$out_path" is a file, not a directory'` is output without calling mkdir (because it already existed).  I just do an `os.is_file` check.

**Comment by Hunam6** [comment]
Okay I get it, very nice work on this PR, congrats 👏

**Pull request merged**
