### PR TITLE
cleanup the whole project

### LINKED ISSUE #76: code needs to be cleaned up

### PR DESCRIPTION
**Pull request by Hunam6**
closes #76

In this PR I made the project really contribution-ready, what I mean is that over the updates the project got really messy. So I cleaned up the project a lot by reorganising all the functions, renaming the ones that needed it in a uniform manner, and commenting each one. I also did some small cleanups of "real" code.

Here is the current layout of the app:
```v
// go2v.v
struct InOutPaths
fn go_to_v() {}
fn convert_and_write() {}

// ast_parser.v
enum TokenizerState
enum TokenType
struct Token
struct Child
struct Tree
fn tokenizer() {}
fn tree_constructor() {}

// utils.v
const get_v_type
const keywords
enum Case
enum Origin
enum Domain
fn set_naming_style() {}
fn format_and_set_naming_style() {}
fn type_to_default_value() {}
fn (VAST) struct_name_to_struct() {}
fn (VAST) stmt_to_string() {}
fn (VAST) find_unused_name() {}
fn (VAST) get_type() {}
fn (VAST) get_name() {}
fn (VAST) get_initial_name() {}
fn (VAST) get_condition() {}
fn (VAST) get_initial_condition() {}
fn not_implemented() {}

// ast_extractor.v
fn ast_extractor() {}
fn (VAST) extract_declaration() {}
fn (VAST) extract_embedded_declaration() {}
fn (VAST) extract_module() {}
fn (VAST) extract_imports() {}
fn (VAST) extract_const_or_enum() {}
fn (VAST) extract_sumtype() {}
fn (VAST) extract_struct() {}
fn (VAST) extract_function() {}
fn (VAST) extract_body() {}
fn (VAST) extract_stmt() {}
fn (VAST) extract_variable() {}
fn (VAST) extract_increment_or_decrement() {}

// file_writer.v
fn file_writer() {}
fn (VAST) write_module() {}
fn (VAST) write_imports() {}
fn (VAST) write_sumtypes() {}
fn (VAST) write_structs() {}
fn (VAST) write_consts() {}
fn (VAST) write_enums() {}
fn (VAST) write_functions() {}
fn (VAST) write_body() {}
fn (VAST) write_stmt() {}

// ast_transformer.v
const strings_to_builtin
const name_equivalence
const string_builder_diffs
fn (VAST) stmt_transformer() {}
fn (VAST) transform_fn_to_decl() {}
fn (VAST) transform_make() {}
fn (VAST) transform_delete() {}
fn (VAST) transform_print() {}
fn (VAST) transform_string_builder() {}
fn (VAST) transform_strings_module() {}

// ast.v
struct VAST
struct Struct
struct StructLike
type Statement

struct XXXStmt ...
```

### CODE REVIEW

**Comment by JalonSolov** [comment]
Very nice!

My only suggestion, to take it a step further, would be to rename the current `@<whatever>` variables to something without `@`.  Like `@const` could be `go_const`.  Etc.

**Comment by Hunam6** [comment]
> Very nice!
My only suggestion, to take it a step further, would be to rename the current @<whatever> variables to something without @. Like @const could be go_const. Etc.

Thank you 🙇

I don't get why this would be better 🤔

**Comment by JalonSolov** [comment]
More descriptive, for one thing.  `@const` is... a const?  But `go_const` is a constant that came from Go.

**Comment by Hunam6** [comment]
I don't agree,
```go
package main

import "fmt"

func main() {
	Const := 43
	fmt.Println(Const)
}
```
how is that clearer
```v
module main

fn main() {
	mut go_const := 43
	println(go_const)
}
```
than that?
```v
module main

fn main() {
	mut @const := 43
	println(@const)
}
```

**Pull request merged**
