### PR TITLE
fix: paths again... with tests

### PR DESCRIPTION
**Pull request by JalonSolov**
More tweaks to path handling, but now tests added to hopefully avoid problems in the future.

I'm sure the tests can be improved, but I put in all the regular cases I could think of...

### CODE REVIEW

**Comment by JalonSolov** [comment]
$@?!@?$ Windows... <sigh> will try testing on my vm.

**Comment by Hunam6** [comment]
I've just extracted the error message, maybe that can save you some time: `cli execution error: failed to open file "C:\Users\hunam\Documents\temp\go2v\path_test_area""`, it gets treated as a file instead of a folder

**Comment by Hunam6** [comment]
I just pushed a tiny tweak because you don't want that when running `go2v test`
dsf

**Comment by JalonSolov** [comment]
It's failing because of a bug in `os.quoted_path` routine in V not handling trailing `\` on Windows paths.  The CI here can be re-run once https://github.com/vlang/v/pull/13705 is merged, and should pass fine.

**Comment by Hunam6** [comment]
Nice, good finding!

**Pull request merged**
