### PR TITLE
Update go2v.v

### PR DESCRIPTION
**Pull request by yaskhan**
Run on Windows, get error with path to 'ast_getter.go'

### CODE REVIEW

**Comment by Hunam6** [comment]
Hey, thanks for your contribution and sorry for the delay.
I tried running `v run . .\transpiler\ast_getter.go -o out` on both PowerShell and CMD and both worked fine without your PR. I mean I got "go is not a keyword" but it's not related.

```
PS C:\Users\hunam\Documents\dev\go2v> v run . .\transpiler\ast_getter.go -o z
converting ".\transpiler\ast_getter.go" -> "z"
Generated output could not be formatted
==================
z:3:8: error: unexpected keyword `go`, expecting name
    1 | module main
    2 | import flag
    3 | import go.ast
      |        ~~
    4 | import go.parser
    5 | import go.token
z:4:8: error: unexpected keyword `go`, expecting name
    2 | import flag
    3 | import go.ast
    4 | import go.parser
      |        ~~
    5 | import go.token
    6 | import os
z:5:8: error: unexpected keyword `go`, expecting name
    3 | import go.ast
    4 | import go.parser
    5 | import go.token
      |        ~~
    6 | import os
    7 | fn main() {flag.parse()

==================
```

**Comment by Hunam6** [comment]
What V version and Go version do you have?

**Comment by yaskhan** [comment]
> What V version and Go version do you have?

go version go1.21.2 windows/amd64

**Comment by Hunam6** [comment]
Try updating to the latest V **and** Go versions and try again, could be the issue

**Review by spytheman — APPROVED** [review]

**Pull request merged**
