### PR TITLE
complex & massive cleanup of `utils.v` functions `get_type`, `get_name`, & `get_namespaces`, rudimentary system adding more informations to not yet implemented features, fix type conversion in struct fields

### PR DESCRIPTION
**Pull request by Hunam6**
- complex & massive cleanup of `utils.v` functions `get_type`, `get_name`, & `get_namespaces`
- add a rudimentary system adding more informations to not yet implemented features
- fix type conversion in struct fields

### CODE REVIEW

**Comment by Hunam6** [comment]
(review requested mostly for the not_implemented function)

**Comment by JalonSolov** [comment]
I don't see the "not implemented" message at all on a normal run.  It just... stops.
```
$ v run . ~/idioms -o /tmp/idioms
converting "/home/jamie/idioms/001a_print_hello_world.go" -> "/tmp/idioms/001a_print_hello_world.v"
converting "/home/jamie/idioms/001b_print_hello_world.go" -> "/tmp/idioms/001b_print_hello_world.v"
converting "/home/jamie/idioms/002a_print_hello_10_times.go" -> "/tmp/idioms/002a_print_hello_10_times.v"
converting "/home/jamie/idioms/002b_print_hello_10_times.go" -> "/tmp/idioms/002b_print_hello_10_times.v"
converting "/home/jamie/idioms/003a_create_a_procedure.go" -> "/tmp/idioms/003a_create_a_procedure.v"
$
```

**Comment by JalonSolov** [comment]
Without the changes in this PR, I saw this:
```
$ v run . ~/idioms -o /tmp/idioms
converting "/home/jamie/idioms/001a_print_hello_world.go" -> "/tmp/idioms/001a_print_hello_world.v"
converting "/home/jamie/idioms/001b_print_hello_world.go" -> "/tmp/idioms/001b_print_hello_world.v"
converting "/home/jamie/idioms/002a_print_hello_10_times.go" -> "/tmp/idioms/002a_print_hello_10_times.v"
converting "/home/jamie/idioms/002b_print_hello_10_times.go" -> "/tmp/idioms/002b_print_hello_10_times.v"
converting "/home/jamie/idioms/003a_create_a_procedure.go" -> "/tmp/idioms/003a_create_a_procedure.v"
Go feature `*ast.BinaryExpr` not currently implemented
Please report the missing feature at https://github.com/vlang/go2v/issues/new
converting "/home/jamie/idioms/003b_create_a_procedure.go" -> "/tmp/idioms/003b_create_a_procedure.v"
Go feature `*ast.FuncLit` not currently implemented
Please report the missing feature at https://github.com/vlang/go2v/issues/new
converting "/home/jamie/idioms/004_create_a_function.go" -> "/tmp/idioms/004_create_a_function.v"
Go feature `*ast.BinaryExpr` not currently implemented
Please report the missing feature at https://github.com/vlang/go2v/issues/new
/tmp/idioms/004_create_a_function.v:3:34: error: invalid expression: unexpected token `,`
    1 | module main
    2 | 
    3 | fn square(x int, ) (int) {return ,
      |                                  ^
    4 | }
    5 |
cli execution error: Generated output could not be formatted:
$
```

**Comment by JalonSolov** [comment]
FYI - there are 324 .go files in the `idioms` dir.

**Comment by Hunam6** [comment]
This should work

**Comment by JalonSolov** [comment]
It does show the error message on the failure, but I still don't see any of the "not implemented" messages:
```
$ v run . ~/idioms -o /tmp/idioms
converting "/home/jamie/idioms/001a_print_hello_world.go" -> "/tmp/idioms/001a_print_hello_world.v"
converting "/home/jamie/idioms/001b_print_hello_world.go" -> "/tmp/idioms/001b_print_hello_world.v"
converting "/home/jamie/idioms/002a_print_hello_10_times.go" -> "/tmp/idioms/002a_print_hello_10_times.v"
converting "/home/jamie/idioms/002b_print_hello_10_times.go" -> "/tmp/idioms/002b_print_hello_10_times.v"
converting "/home/jamie/idioms/003a_create_a_procedure.go" -> "/tmp/idioms/003a_create_a_procedure.v"
converting "/home/jamie/idioms/003b_create_a_procedure.go" -> "/tmp/idioms/003b_create_a_procedure.v"
converting "/home/jamie/idioms/004_create_a_function.go" -> "/tmp/idioms/004_create_a_function.v"
/tmp/idioms/004_create_a_function.v:3:34: error: invalid expression: unexpected token `,`
    1 | module main
    2 | 
    3 | fn square(x int, ) (int) {return ,
      |                                  ^
    4 | }
    5 |
cli execution error: Generated output could not be formatted:
$
```

**Comment by Hunam6** [comment]
Should be good now

**Review by JalonSolov — APPROVED** [review]
That's got it now!

**Pull request merged**
